### ISSUE TITLE
Implement time-dependent boundaries in automata

### ISSUE THREAD

**Issue by SaraImari** [ELIFE-ASU/Neet#13]

**Comment by dglmoore** [comment]
@SaraImari, do you have any thoughts on what you'd like this to look like? What we have now will accommodate time-dependent boundary conditions; the user just has to be explicit in how they change. 

For example, suppose you have a function `next_conditions(t)` which returns a tuple of boundary conditions (e.g. (1,0)) based on the current time-step `t`, then you could do something like

```python
ca = ECA(30, boundary=(0,0))
lattice = [0,0,1,0,0]
for t in range(10):
    ca.boundary = next_condition(t)
    ca.update(lattice)
```

However, this approach will not be compatible with the built-in analysis functions as they stand. Do you have any thoughts?
