### ISSUE TITLE
Sensitivity for generic networks

### ISSUE THREAD

**Issue by dglmoore** [ELIFE-ASU/Neet#130]

**Comment by bcdaniels** [comment]
I think we mean "generic boolean networks"?  We could define sensitivity more generally, but that would require more thought.

**Comment by bcdaniels** [comment]
Also, I forgot that this is already done (see #89 and #113).  Ha :)  Easiest homework ever!

**Comment by dglmoore** [comment]
@bcdaniels Huh. You are right. I guess this means I'll have to find you a new issue. :wink:
