### ISSUE TITLE
Attractor Landscape Features

### ISSUE THREAD

**Issue by dglmoore** [ELIFE-ASU/Neet#15]
We need a basic set of attractor-related functionality.

Minimal Desired Functionality:
- Identify Attractors
- Distribution of Basin Sizes, 
- Basic Network Measures
- Longest Trajectory
- Average Trajectory Length

**Comment by bcdaniels** [comment]
Also desired: Basin Entropy, as defined in https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.98.158701

**Comment by dglmoore** [comment]
@bcdaniels Basin entropy seems so obvious now, but I never thought of it. We'll definitely implement it!
