### ISSUE TITLE
Random Boolean Network Module

### ISSUE THREAD

**Issue by dglmoore** [ELIFE-ASU/Neet#33]
**This issue is still under discussion. Please contribute via the comment section below!**

For many purposes we need a generic collection of random network generation functions. We can break these functions into two types: **random creation** and **random shuffle**.

### Random Creation
We need to be able to construct random networks without providing a starting network, e.g. random Erdős–Rényi, Barabási–Albert, etc...

### Random Shuffle
Random shuffling takes a network as a starting point and "shuffles" its edges about randomly while preserving some topological features of the network. As per in-person discussion, we've  compiled a (likely incomplete) list of features that might be worth preserving. They are broken into two types: *global* and *local*

#### Global Features
1. Number of nodes
2. Number of edges
    a. Number of activation edges
    b. Number of inhibitive edges
3. Degree Distribution

#### Local Features
1. Degree Sequence
    a. Incoming number of edges
    b. Outgoing number of edges
2. Weights
3. Thresholds

## Proposed API
We do not yet have an API in mind. What we have so far decided on is having a module `neet.boolean.random` which contains a collection of random generation functions. The two types, *creation* vs *shuffle* might have names such as:

```python
"""
Create a fresh, random network using `args...`, e.g. number of nodes, number of edges, probability of an edge, etc...
"""
def random(args...)

"""
Shuffle a network `net` according to the `args...`.
"""
def shuffle(net, args...)
```

**Comment by siyuzhou** [comment]
For network shuffling , we have to consider whether to change the wiring in-place or return a rewired network leaving the original intact. I did the latter.

**Comment by dglmoore** [comment]
@siyuzhou, I believe that @thyamu is mutating a copy.

**Comment by siyuzhou** [comment]
Right now all the randomization functions randomize the activating conditions. We could consider adding a function that conserves the original condition table and only rewires the connections. We may need to rename the functions to avoid ambiguity of the descriptions.

**Comment by dglmoore** [comment]
From [#neet](https://elife-asu.slack.com/archives/C5ZT4N7MW/p1522265115000388) on [slack](elife-asu.slack.com)
> I'm thinking about how we've implemented our random network generation functions. We seem to be in agreement that it needs to be revamped in the coming week/months. Do we think we could come up with a way to make the algorithm's composable?
> 
> By this I mean, right now we write one monolithic function which keeps the structure fixed and let's you provide arguments which tweak how the network is varied, i.e. an argument to restrict to irreducible functions, to canalyzing functions, etc... Can we come up with a randomization scheme that allows the user to compose constraints on the randomization?
> 
> For example we create a class called `RandomNetworkGenerator` (or something pithier) which represents a minimally constrained random network generation algorithm. Then we create classes for each kind of constraint, e.g. `FixedStructureConstraint`, `IrreducibleConstraint`, etc... And then we can add or otherwise compose those constraints with the `RandomNetworkGenerator` to produce a class that generates networks that satisfy those constraints? This would be a beautiful solution to our current randomization woes.
>
> I think we could make that work. Does anyone else have any thoughts?

**Comment by siyuzhou** [comment]
I haven't thought about creating classes. I was thinking about creating small pieces of functions that specialize in generating connections or conditions. A single function would still be created that would glue the small pieces according to parameter switches. This line of thought is similar to what we did but is a little more flexible. 

It's hard for me to know how objects as constraints integrate with the random generator for a lack of experience. (Do they instruct the generator what to do by returning boolean values?) I like this idea and would like to see it work.

**Comment by siyuzhou** [comment]
By the way how did you post it from #neet on #slack? I don't see the message on Slack.
