### ISSUE TITLE
Information Analysis

### ISSUE THREAD

**Issue by dglmoore** [ELIFE-ASU/Neet#35]
## Description
One of the major goals for this project is to be able to directly ask for the informational architecture of a network and have the library handle the bookkeeping required.

## Proposed API
We propose introducing a module `neet.information` which provides a collection of information related functions, e.g.

```python
def transfer_entropy(net, k, timesteps, size=None, local=False):
    """
    :returns: the transfer entropy for each pair of nodes as a matrix
    """
    ...

def active_information(net, k, timesteps, size=None, local=False):
    """
    :returns: the active information for each node as a vector
    """
    ...
```

Together with a class which computes an entire suite of measures at construction:

```python
class InfoArchitecture(object):
    def __init__(self, net, k, timesteps, size=None, local=False):
        ...

    @property
    def transfer_entropy(self):
         return self.__transfer_entropy

    @property
    def active_information(self):
        return self.__active_information
```

**Comment by dglmoore** [comment]
Is everyone pleased with the status of this issue? Ready to close it?

**Comment by hbsmith** [comment]
yeah, i vote to close
