### ISSUE TITLE
Rename basins function

### ISSUE THREAD

**Issue by dglmoore** [ELIFE-ASU/Neet#51]
## Description
Should we rename the `neet.synchronous.basins` function to something more descriptive, say `neet.synchronous.attractor_basins`?

## In favor
Clearer and more specific is (almost) always better. It won't take must to rename the function

## Against
The name is already fairly clear. It is unlikely that it will be mistaken for something else or that the end users would miss it.

**Comment by thyamu** [comment]
I think it is already clear. I can not think of cases where the name basin indicates other things.

**Comment by siyuzhou** [comment]
I don't think it needs to be changed. There is little confusion.
