### ISSUE TITLE
In-place State Update

### ISSUE THREAD

**Issue by dglmoore** [ELIFE-ASU/Neet#54]
The `LogicNetwork.update` method performs the updates on a copy of the network; however, most of the landscape related functions, e.g. `synchronous.transitions`, expect an in-place update to work correctly. We should modify the `LogicNetwork.update` to perform the updates in-place.

@dglmoore should have caught this during code review... shuuunnnn.... 👎

**Comment by siyuzhou** [comment]
I'll have it changed once #53 is merged to avoid merge conflicts. It should be an easy fix.

**Comment by siyuzhou** [comment]
I went ahead and made the change.
