### ISSUE TITLE
Landscape topology

### ISSUE THREAD

**Issue by bcdaniels** [ELIFE-ASU/Neet#67]
We'd like something analogous to the "architecture" structure that calculates everything about the topology of state transition graph.  This would include attractors, attractor basins, trajectory lengths, the transition graph in-degree, etc.

**Comment by dglmoore** [comment]
Here's the basic structure I have in mind. Please add additional features we'd like to see as additional comments.

```python
class LandscapeTopology:
    def __init__(self, net, size=None):
        pass
    def attractors(self):
        pass
    def basins(self):
        pass
    def graph(self):
        pass
    def distance_to_attractor(self):
        pass
    def in_degree(self):
        pass
```
