### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bcdaniels** [ELIFE-ASU/Neet#70]
Documentation!!!

**Comment by thyamu** [comment]
Documentation for neet.synchronous.transition_graph described "encode" but when I use that, I get TypeError: transition_graph() got an unexpected keyword argument 'encode'

**Comment by thyamu** [comment]
For Synchronous API, the use of "encode" is ambiguous. The function of this argument is clear but when users want to have encoded and uncoded version both or mapping between them, the documentation is not clear about that.

**Comment by hbsmith** [comment]
I think I addressed this in the pull request i submitted a week or two ago,
#121.
