### ISSUE TITLE
Identify causal network edges

### ISSUE THREAD

**Issue by bcdaniels** [ELIFE-ASU/Neet#78]
We want a way to identify causal network edges.  

This could be used to filter edges that are output to a networkx object, or to calculate the number of causal edges (as opposed to the total number of edges, which may be misleading, especially in random networks).

**Comment by dglmoore** [comment]
@bcdaniels What's a 'causal network edge'?

**Comment by bcdaniels** [comment]
A causal edge from A to B means that, for at least one state of the system, the state of A affects the next state of B.

**Comment by bcdaniels** [comment]
Addressed by #82
