### ISSUE TITLE
Identify activating vs inhibiting edges of a LogicNetwork

### ISSUE THREAD

**Issue by hbsmith** [ELIFE-ASU/Neet#80]
Is it possible to look at `LogicNetwork.table` and identify the edges that are inhibiting and those that are activating? If possible, this would be useful to add to `neighbors` and for network connectivity purposes.

**Comment by dglmoore** [comment]
@hbsmith Logic networks admit inhibiting and activating edges, but they also allow for edges that are neither/both.  For example, consider an XOR node (C) which depends on (A,B):

| A | B | C |
| - | - | - |
| 0 | 0 | 0 |
| 1 | 0 | 1 |
| 0 | 1 | 1 |
| 1 | 1 | 0 |

Is A → C inhibiting or activating?

So, I think we should avoid describing logical edges as activating or inhibitive, or we should have additional types of edges to describe the more complex types as above.

**Comment by dglmoore** [comment]
@hbsmith What are we thinking about this? Should we keep it open and pursue an implementation, or should we close as wont-fix?

**Comment by hbsmith** [comment]
I still think this would be a nice feature, but it's not a priority. Does wont-fix imply it's off the table indefinitely? If so, maybe a `low-priority` label would be more appropriate.

**Comment by hbsmith** [comment]
We don't have a good plan in mind for how to execute this right now.
