### ISSUE TITLE
Network-type Conversions

### ISSUE THREAD

**Issue by dglmoore** [ELIFE-ASU/Neet#84]
## Description
It would be useful to be able to convert `WTNetworks`, for example, into `LogicNetwork`s.

## Proposed API
Create a submodule `neet.boolean.conv` with functions such as
```python
def to_logic_network(net, size=None):
    pass

def to_wt_network(net, size=None):
    pass
```
**Suggestions on function names are very welcome.**

**Comment by hbsmith** [comment]
I like those names. Is there a reason this shouldn't be extended to ECAs (which are also boolean), and scoped outside the boolean module? (or perhaps just not a priority right now)

**Comment by dglmoore** [comment]
The functions would take any network as an argument, this includes `ECA`s, and _attempt_ to convert them to the desired network type. I put this in `neet.boolean.conv` because the target types of these functions are Boolean networks. We could just as well put these functions in `neet.conv`.

**Comment by hbsmith** [comment]
Got it, sounds good.
