### ISSUE TITLE
Implementing Sensitivity with neighbors function

### ISSUE THREAD

**Issue by dglmoore** [ELIFE-ASU/Neet#86]
## Description
The various sensitivity functions take advantage `LogicNetwork`'s logic table to improve performance, but `WTNetwork`s do not yet benefit from the use of structural information. Might we be able to use, for example, the [`neighbors`](https://github.com/ELIFE-ASU/Neet/blob/86928c37e262fdf9c1e10294e9c6e50f4d8ac0d3/neet/interfaces.py#L77) function to make the implementation of [`average_difference_matrix`](https://github.com/ELIFE-ASU/Neet/blob/86928c37e262fdf9c1e10294e9c6e50f4d8ac0d3/neet/sensitivity.py#L97) type-agnostic without performance penalties?

**Comment by bcdaniels** [comment]
Agreed!  I'll see if I can get this implemented in the next few days.
