### ISSUE TITLE
Add existing datasets to NEET as a submodule

### ISSUE THREAD

**Issue by hbsmith** [ELIFE-ASU/Neet#9]
Includes Fission yeast, budding yeast, p53, cortical network, etc... (what other's specifically?)

**Comment by dglmoore** [comment]
I'm thinking that the best approach will be to create a submodule `neet.boolean.examples` which loads each of the networks from a file `data/<network>.dat`. For example, we might have a file `data/s_pombe.dat` which contains the necessary information for constructing a `neet.boolean.WTNetwork` for the fission yeast. Then within the `neet.boolean.examples` module we'd have
```python
s_pombe = WTNetwork.read("data/s_pombe.dat", binary=True)
```

To use the example networks, just import them and go:
```python
>>> from neet.boolean.examples import s_pombe
>>> from neet.landscape import trajectory
>>> list(trajectory(s_pombe, [1,0,1,1,0,0,1,0,0], n=8, encode=False))
...
```

It would be great if people would comment with networks that they would like to see as built-in examples.

**Comment by hbsmith** [comment]
Added the "best" networks from the mouse cortical network, according to the edges outlined in Giacomantonio 2010, figure 7B and 7C. The added networks include all combinations of the desired initial and final node states, for both the anterior and posterior networks, for the two "best" edge configurations. This results in a total of 8 added networks from the mouse cortical GRN.
